jonk:
  sonarqube:
    host-url: "http://host.docker.internal:9000"
    token: "squ_83f76ad0fb3ff1dd13cd5e6ec038b49432fc9909"
    poll-interval: 2s
    quality-gate-timeout: 5m
    docker-compose-path: "./docker-dev-env/docker-compose.yml"

  keycloak:
    server-url: http://host.docker.internal:8180
    realm: Jonk
    client-id: jonk-back
    client-secret: jonk-secret
